### ISSUE TITLE
randomly generate left wall for enigma

### ISSUE THREAD

**Issue by preethika-ajay** [acmpesuecc/Ciphers#1]
# randomly generate left wall for enigma
## Description
The Enigma Cipher is currently built around a static rotor and reflector configuration. This enhancement requires you to make the left wall of the rotor and the reflector change everytime the code is run.
## Understanding code
The left wall is a random sequence of all the 26 alphabets. Currently, the left wall configuration is read from a textfile secret_key.txt. The left wall is expected to change everytime randomly everytime the code is run for both the rotors and the reflector. To know what the reflector and rotor are, refer to enigma_explain.txt

<hr>
Bounty points alloted : 75<br>
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

**Comment by sewimpractical** [comment]
Thank you :)

**Comment by JoyenBenitto** [comment]
can I work on this issue
